// Fantasy team rosters - auto-generated
// Last updated: 2026-02-03T03:37:42.515196Z

const ROSTER_DATA = {
  "rosters": {
    "Pinkston": [
      "Jalen Hurts",
      "Emeka Egbuka",
      "Josh Downs",
      "Derrick Henry",
      "Pat Freiermuth",
      "Tyrone Tracy Jr.",
      "Tony Pollard",
      "Harold Fannin Jr.",
      "DK Metcalf",
      "Troy Franklin",
      "C.J. Stroud",
      "Philip Rivers"
    ],
    "CP": [
      "Tyler Shough",
      "Terry McLaurin",
      "Stefon Diggs",
      "Ashton Jeanty",
      "Kyle Pitts Sr.",
      "Jaylen Warren",
      "Rhamondre Stevenson",
      "Lamar Jackson",
      "Blake Corum",
      "Davante Adams",
      "Oronde Gadsden",
      "Ray Davis"
    ],
    "Rizzo": [
      "Dak Prescott",
      "CeeDee Lamb",
      "Jakobi Meyers",
      "Jacory Croskey-Merritt",
      "Mike Gesicki",
      "Bucky Irving",
      "James Cook III",
      "DeVonta Smith",
      "Ladd McConkey",
      "Woody Marks",
      "Michael Pittman Jr.",
      "Michael Mayer",
      "Brock Bowers"
    ],
    "Farber": [
      "Trevor Lawrence",
      "Chris Godwin Jr.",
      "Alec Pierce",
      "Saquon Barkley",
      "Mark Andrews",
      "David Montgomery",
      "RJ Harvey",
      "Keenan Allen",
      "Jayden Higgins",
      "Tyler Allgeier",
      "Audric Estime",
      "Colby Parkinson",
      "Sam LaPorta"
    ],
    "Dues": [
      "Drake Maye",
      "Christian Watson",
      "Brian Thomas Jr.",
      "Samaje Perine",
      "Colston Loveland",
      "Khalil Shakir",
      "Zay Flowers",
      "TreVeyon Henderson",
      "Rashee Rice",
      "Emanuel Wilson",
      "Luther Burden III",
      "Jaylen Wright"
    ],
    "Jett": [
      "Bo Nix",
      "Drake London",
      "Mike Evans",
      "Isiah Pacheco",
      "Dallas Goedert",
      "Nico Collins",
      "Jordan Addison",
      "Sam Darnold",
      "Zach Charbonnet",
      "Xavier Worthy",
      "Kyle Monangai",
      "Parker Washington",
      "Garrett Wilson"
    ],
    "Rick": [
      "Baker Mayfield",
      "Darius Slayton",
      "Romeo Doubs",
      "Jonathan Taylor",
      "Jake Ferguson",
      "Marvin Harrison Jr.",
      "Tyjae Spears",
      "Jordan Love",
      "Matthew Golden",
      "Kareem Hunt",
      "Isaiah Likely",
      "Rashid Shaheed"
    ],
    "Lloyd": [
      "Matthew Stafford",
      "Courtland Sutton",
      "Tee Higgins",
      "Javonte Williams",
      "Trey McBride",
      "Jahmyr Gibbs",
      "Aaron Jones Sr.",
      "DJ Moore",
      "Jerry Jeudy",
      "Cooper Kupp",
      "Tank Bigsby",
      "Jalen Coker"
    ],
    "Stern": [
      "Jacoby Brissett",
      "Jameson Williams",
      "Quentin Johnston",
      "De'Von Achane",
      "Hunter Henry",
      "Bijan Robinson",
      "Omarion Hampton",
      "Taysom Hill",
      "Juwan Johnson",
      "Justin Herbert",
      "Michael Carter",
      "Josh Johnson"
    ],
    "JB": [
      "Caleb Williams",
      "Chris Olave",
      "Tetairoa McMillan",
      "Kyren Williams",
      "AJ Barner",
      "Justin Jefferson",
      "Kenneth Walker III",
      "Jared Goff",
      "Dalton Kincaid",
      "Sean Tucker",
      "Adonai Mitchell",
      "Emari Demercado",
      "J.K. Dobbins"
    ],
    "Yonk": [
      "Josh Allen",
      "Jaxon Smith-Njigba",
      "George Pickens",
      "Christian McCaffrey",
      "Tyler Warren",
      "Rico Dowdle",
      "Jaylen Waddle",
      "Chris Rodriguez Jr.",
      "Kimani Vidal",
      "Darnell Mooney",
      "Evan Hull",
      "Chuba Hubbard"
    ],
    "Ben": [
      "Joe Burrow",
      "Ja'Marr Chase",
      "Michael Wilson",
      "Dylan Sampson",
      "Dalton Schultz",
      "D'Andre Swift",
      "Brenton Strange",
      "George Kittle",
      "Deebo Samuel",
      "Darren Waller",
      "Brian Robinson Jr.",
      "Adam Thielen"
    ],
    "Rich": [
      "Brock Purdy",
      "A.J. Brown",
      "Wan'Dale Robinson",
      "Chase Brown",
      "Chig Okonkwo",
      "Josh Jacobs",
      "Tre Tucker",
      "Ricky Pearsall",
      "Nick Chubb",
      "Devin Singletary",
      "Bhayshul Tuten",
      "Jake Tonges"
    ],
    "Andrew": [
      "Geno Smith",
      "Puka Nacua",
      "Amon-Ra St. Brown",
      "Travis Etienne Jr.",
      "Travis Kelce",
      "Jauan Jennings",
      "Kenneth Gainwell",
      "Jayden Reed",
      "Breece Hall",
      "Jaxson Dart",
      "Alvin Kamara",
      "Malik Davis"
    ]
  },
  "updated": "2026-02-03T03:37:42.515196Z"
};
